title: Joshternet
description: >-
  The Joshternet is an open, decentralized network for people who identify as
  Josh and the independent websites they call home.
url: https://joshternet.org
baseurl: ""
lang: en
locale: en_US
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/joshternet-social.png
        height: 630
        width: 1200
        alt: Joshternet logo

include:
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md